### ISSUE TITLE
Deployment with different default names fails

### ISSUE THREAD

**Issue by mtodor** [redhat-developer/observability-operator#117]
I'm trying to deploy an operator with different default names for AlertManger, Grafana, and Prometheus, but it does not work. I would be really grateful if someone could point me in the right direction or tell me what I'm doing wrong.

**Steps - tested with OpenShift**
Everything is done by applying resources over the `oc` command.
1. add namespace where an operator will work
2. add catalog source
3. add secret for GitHub repo
4. add operator group
5. add `observability-operator-no-init` configmap - I'm doing this to avoid that after the subscription operator kicks in and creates a custom resource on its own
6. add a subscription for the operator
7. add my custom resource with default names
```
apiVersion: observability.redhat.com/v1
kind: Observability
metadata:
  name: test-observability-stack
  namespace: test-observability
spec:
  configurationSelector:
    matchLabels:
      configures: observability-operator
  alertManagerDefaultName: 'test-alertmanager'
  grafanaDefaultName: 'test-grafana'
  prometheusDefaultName: 'test-prometheus'
  resyncPeriod: 1h
  retention: 45d
  selfContained:
    alertManagerResourceRequirement: {}
    disableBlackboxExporter: true
    grafanaOperatorResourceRequirement: {}
    prometheusOperatorResourceRequirement: {}
    prometheusResourceRequirement: {}

```
8. delete `observability-operator-no-init` configmag

**Expect**
The operator starts with initialization and creates AlertManager, Grafana, and Prometheus operators with default names defined in my custom resource.

**Problem**
I'm getting the following error in `observability-operator-controller-manager`:
```
..
2022-05-12T06:08:40.835Z	DEBUG	controller-runtime.webhook.webhooks	received request	{"webhook": "/validate-observability-redhat-com-v1-observability", "UID": "5c7d15ef-5e37-441d-80a7-8a6dd2dc60a8", "kind": "observability.redhat.com/v1, Kind=Observability", "resource": {"group":"observability.redhat.com","version":"v1","resource":"observabilities"}}
2022-05-12T06:08:40.838Z	INFO	observability-resource	validate update	{"name": "test-observability-stack"}
2022-05-12T06:08:40.917Z	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-observability-redhat-com-v1-observability", "code": 403, "reason": "cannot update AlertManagerDefaultName after cr creation", "UID": "5c7d15ef-5e37-441d-80a7-8a6dd2dc60a8", "allowed": false}
2022-05-12T06:08:40.928Z	ERROR	controllers.Observability	Failed to remove pre-existing operand with missing or incorrect managed label	{"error": "admission webhook \"vobservability.kb.io\" denied the request: cannot update AlertManagerDefaultName after cr creation"}
github.com/go-logr/zapr.(*zapLogger).Error
	/opt/app-root/src/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
github.com/redhat-developer/observability-operator/v3/controllers.(*ObservabilityReconciler).InitializeOperand
	/workspace/controllers/observability_controller.go:257
main.main.func1
	/workspace/main.go:116
github.com/redhat-developer/observability-operator/v3/runners.(*OperandInitializer).Start
	/workspace/runners/generic_runner.go:16
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/manager/internal.go:661
2022-05-12T06:08:40.928Z	ERROR	setup	unable to create or update operand	{"controller": "Observability", "error": "admission webhook \"vobservability.kb.io\" denied the request: cannot update AlertManagerDefaultName after cr creation"}
github.com/go-logr/zapr.(*zapLogger).Error
	/opt/app-root/src/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
main.main.func1
	/workspace/main.go:117
github.com/redhat-developer/observability-operator/v3/runners.(*OperandInitializer).Start
	/workspace/runners/generic_runner.go:16
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1
	/opt/app-root/src/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/manager/internal.go:661
2022-05-12T06:08:40.928Z	INFO	controller	Stopping workers	{"reconcilerGroup": "observability.redhat.com", "reconcilerKind": "Observability", "controller": "observability"}
2022-05-12T06:08:40.928Z	INFO	controller-runtime.webhook	shutting down webhook server
2022-05-12T06:08:40.929Z	ERROR	setup	problem running manager	{"error": "admission webhook \"vobservability.kb.io\" denied the request: cannot update AlertManagerDefaultName after cr creation"}
github.com/go-logr/zapr.(*zapLogger).Error
	/opt/app-root/src/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
main.main
	/workspace/main.go:125
runtime.main
	/usr/lib/golang/src/runtime/proc.go:225
```

Maybe the problem could be avoided if I would be able to create my custom resource before adding a subscription. But at that point, I'm missing CRD in OpenShift. And CRD is added when a subscription is created.
