### ISSUE TITLE
allow federation configuration to specify metric_relabel_configs

### ISSUE THREAD

**Issue by k-wall** [redhat-developer/observability-operator#198]
I'd like to suggest a new feature that would allow observability to express `metric_relabel_configs` in its federation configuration.  

My specific use-case is to allow us to pass configuration that will drop the `prometheus_replica` label from kubelet metrics originating from OpenShift.  Under some circumstances, we see the same metric delivered from two prometheus replicas, and this breaks queries.

However, I believe the feature would have wider utility for instance,  letting users drop labels from a federated source that are superfluous. 

The observability operator would be [changed](https://github.com/redhat-developer/observability-operator/blob/main/controllers/model/prometheus_resources.go#L151) so the emitted federation includes an optional `metric_relabel_configs` array. 

```yaml
- job_name: openshift-monitoring-federation
  honor_labels: true
  honor_timestamps: true
  params:
    match[]:
    - console_url
    - cluster_version
    - cluster_infrastructure_provider
  metric_relabel_configs:
    - source_labels: [id]
      regex: '^static-agent$'
      action: drop  
```

If I could get some feedback on the idea from the project's maintainers, that would be great.
